paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      # actionlint doesn't yet recognize GitHub's "$/" self-repository uses: syntax.
      # https://github.com/rhysd/actionlint/issues/711
      - 'specifying action "\$/.+" in invalid format because ref is missing'
