# .github/workflows/pre-commit-autoupdate.yml
name: Pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9am

permissions:
  pull-requests: write

jobs:
  autoupdate:
    if: github.event_name != 'schedule' || github.repository == 'Calysto/maintainer_tools'
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false
      - uses: ./actions/pre-commit-autoupdate
        with:
          app-id: ${{ vars.APP_ID }}
          app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
